// Code generated by pigeon; DO NOT EDIT.

package parser

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"

	"github.com/DaveXro/eventrules/ast"
)

func splitComponents(comp interface{}) []interface{} {
	if comp == nil {
		return nil
	}

	return comp.([]interface{})
}

var g = &grammar{
	rules: []*rule{
		{
			name: "Input",
			pos:  position{line: 23, col: 2, offset: 398},
			expr: &actionExpr{
				pos: position{line: 23, col: 11, offset: 407},
				run: (*parser).callonInput1,
				expr: &seqExpr{
					pos: position{line: 23, col: 11, offset: 407},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 23, col: 11, offset: 407},
							label: "root",
							expr: &ruleRefExpr{
								pos:  position{line: 23, col: 16, offset: 412},
								name: "Trigger",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 23, col: 24, offset: 420},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 23, col: 26, offset: 422},
							label: "condition",
							expr: &ruleRefExpr{
								pos:  position{line: 23, col: 36, offset: 432},
								name: "Condition",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 23, col: 46, offset: 442},
							name: "_",
						},
						&zeroOrMoreExpr{
							pos: position{line: 23, col: 48, offset: 444},
							expr: &seqExpr{
								pos: position{line: 23, col: 49, offset: 445},
								exprs: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 23, col: 49, offset: 445},
										name: "Comment",
									},
									&ruleRefExpr{
										pos:  position{line: 23, col: 57, offset: 453},
										name: "_",
									},
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 23, col: 61, offset: 457},
							label: "conditions",
							expr: &zeroOrMoreExpr{
								pos: position{line: 23, col: 72, offset: 468},
								expr: &seqExpr{
									pos: position{line: 23, col: 73, offset: 469},
									exprs: []interface{}{
										&litMatcher{
											pos:        position{line: 23, col: 73, offset: 469},
											val:        "otherwise",
											ignoreCase: false,
											want:       "\"otherwise\"",
										},
										&ruleRefExpr{
											pos:  position{line: 23, col: 85, offset: 481},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 23, col: 87, offset: 483},
											name: "Condition",
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 23, col: 99, offset: 495},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "Trigger",
			pos:  position{line: 45, col: 2, offset: 1041},
			expr: &actionExpr{
				pos: position{line: 45, col: 13, offset: 1052},
				run: (*parser).callonTrigger1,
				expr: &seqExpr{
					pos: position{line: 45, col: 13, offset: 1052},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 45, col: 13, offset: 1052},
							name: "_",
						},
						&zeroOrMoreExpr{
							pos: position{line: 45, col: 15, offset: 1054},
							expr: &seqExpr{
								pos: position{line: 45, col: 16, offset: 1055},
								exprs: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 45, col: 16, offset: 1055},
										name: "Comment",
									},
									&ruleRefExpr{
										pos:  position{line: 45, col: 24, offset: 1063},
										name: "_",
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 45, col: 28, offset: 1067},
							val:        "ON",
							ignoreCase: false,
							want:       "\"ON\"",
						},
						&ruleRefExpr{
							pos:  position{line: 45, col: 33, offset: 1072},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 45, col: 35, offset: 1074},
							label: "eventName",
							expr: &ruleRefExpr{
								pos:  position{line: 45, col: 45, offset: 1084},
								name: "TriggerName",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 45, col: 57, offset: 1096},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "TriggerName",
			pos:  position{line: 50, col: 2, offset: 1210},
			expr: &actionExpr{
				pos: position{line: 50, col: 17, offset: 1225},
				run: (*parser).callonTriggerName1,
				expr: &seqExpr{
					pos: position{line: 50, col: 17, offset: 1225},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 50, col: 17, offset: 1225},
							name: "VariableName",
						},
						&litMatcher{
							pos:        position{line: 50, col: 30, offset: 1238},
							val:        ":",
							ignoreCase: false,
							want:       "\":\"",
						},
						&ruleRefExpr{
							pos:  position{line: 50, col: 34, offset: 1242},
							name: "VariableName",
						},
					},
				},
			},
		},
		{
			name: "Condition",
			pos:  position{line: 58, col: 2, offset: 1417},
			expr: &actionExpr{
				pos: position{line: 58, col: 15, offset: 1430},
				run: (*parser).callonCondition1,
				expr: &seqExpr{
					pos: position{line: 58, col: 15, offset: 1430},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 58, col: 15, offset: 1430},
							name: "_",
						},
						&zeroOrMoreExpr{
							pos: position{line: 58, col: 17, offset: 1432},
							expr: &seqExpr{
								pos: position{line: 58, col: 18, offset: 1433},
								exprs: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 58, col: 18, offset: 1433},
										name: "Comment",
									},
									&ruleRefExpr{
										pos:  position{line: 58, col: 26, offset: 1441},
										name: "_",
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 58, col: 30, offset: 1445},
							val:        "when",
							ignoreCase: false,
							want:       "\"when\"",
						},
						&ruleRefExpr{
							pos:  position{line: 58, col: 37, offset: 1452},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 58, col: 39, offset: 1454},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&ruleRefExpr{
							pos:  position{line: 58, col: 42, offset: 1457},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 58, col: 44, offset: 1459},
							label: "ruleField",
							expr: &oneOrMoreExpr{
								pos: position{line: 58, col: 54, offset: 1469},
								expr: &choiceExpr{
									pos: position{line: 58, col: 56, offset: 1471},
									alternatives: []interface{}{
										&seqExpr{
											pos: position{line: 58, col: 56, offset: 1471},
											exprs: []interface{}{
												&ruleRefExpr{
													pos:  position{line: 58, col: 56, offset: 1471},
													name: "RuleField",
												},
												&ruleRefExpr{
													pos:  position{line: 58, col: 66, offset: 1481},
													name: "_",
												},
											},
										},
										&seqExpr{
											pos: position{line: 58, col: 70, offset: 1485},
											exprs: []interface{}{
												&ruleRefExpr{
													pos:  position{line: 58, col: 70, offset: 1485},
													name: "Comment",
												},
												&ruleRefExpr{
													pos:  position{line: 58, col: 78, offset: 1493},
													name: "_",
												},
											},
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 58, col: 82, offset: 1497},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 58, col: 85, offset: 1500},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
						&ruleRefExpr{
							pos:  position{line: 58, col: 89, offset: 1504},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 58, col: 91, offset: 1506},
							label: "block",
							expr: &ruleRefExpr{
								pos:  position{line: 58, col: 97, offset: 1512},
								name: "StatementBlock",
							},
						},
					},
				},
			},
		},
		{
			name: "RuleField",
			pos:  position{line: 79, col: 2, offset: 1944},
			expr: &actionExpr{
				pos: position{line: 79, col: 15, offset: 1957},
				run: (*parser).callonRuleField1,
				expr: &seqExpr{
					pos: position{line: 79, col: 15, offset: 1957},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 79, col: 15, offset: 1957},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 79, col: 21, offset: 1963},
								name: "RuleClause",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 79, col: 32, offset: 1974},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 79, col: 34, offset: 1976},
							label: "alt",
							expr: &zeroOrOneExpr{
								pos: position{line: 79, col: 39, offset: 1981},
								expr: &seqExpr{
									pos: position{line: 79, col: 40, offset: 1982},
									exprs: []interface{}{
										&litMatcher{
											pos:        position{line: 79, col: 40, offset: 1982},
											val:        "OR",
											ignoreCase: false,
											want:       "\"OR\"",
										},
										&ruleRefExpr{
											pos:  position{line: 79, col: 45, offset: 1987},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 79, col: 47, offset: 1989},
											name: "RuleClause",
										},
										&ruleRefExpr{
											pos:  position{line: 79, col: 58, offset: 2000},
											name: "_",
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 79, col: 62, offset: 2004},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "RuleClause",
			pos:  position{line: 99, col: 2, offset: 2305},
			expr: &choiceExpr{
				pos: position{line: 99, col: 16, offset: 2319},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 99, col: 16, offset: 2319},
						run: (*parser).callonRuleClause2,
						expr: &seqExpr{
							pos: position{line: 99, col: 16, offset: 2319},
							exprs: []interface{}{
								&labeledExpr{
									pos:   position{line: 99, col: 16, offset: 2319},
									label: "field",
									expr: &ruleRefExpr{
										pos:  position{line: 99, col: 22, offset: 2325},
										name: "VariableName",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 99, col: 35, offset: 2338},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 99, col: 37, offset: 2340},
									label: "null",
									expr: &ruleRefExpr{
										pos:  position{line: 99, col: 42, offset: 2345},
										name: "EmptyCheck",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 99, col: 53, offset: 2356},
									name: "_",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 121, col: 6, offset: 2705},
						run: (*parser).callonRuleClause10,
						expr: &seqExpr{
							pos: position{line: 121, col: 6, offset: 2705},
							exprs: []interface{}{
								&labeledExpr{
									pos:   position{line: 121, col: 6, offset: 2705},
									label: "field",
									expr: &ruleRefExpr{
										pos:  position{line: 121, col: 12, offset: 2711},
										name: "VariableName",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 121, col: 25, offset: 2724},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 121, col: 27, offset: 2726},
									label: "op",
									expr: &ruleRefExpr{
										pos:  position{line: 121, col: 30, offset: 2729},
										name: "ComparisonOperator",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 121, col: 49, offset: 2748},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 121, col: 51, offset: 2750},
									label: "rhs",
									expr: &ruleRefExpr{
										pos:  position{line: 121, col: 55, offset: 2754},
										name: "ConditionValue",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 121, col: 70, offset: 2769},
									name: "_",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ConditionValue",
			pos:  position{line: 135, col: 2, offset: 2996},
			expr: &actionExpr{
				pos: position{line: 135, col: 20, offset: 3014},
				run: (*parser).callonConditionValue1,
				expr: &labeledExpr{
					pos:   position{line: 135, col: 20, offset: 3014},
					label: "rhsVal",
					expr: &choiceExpr{
						pos: position{line: 135, col: 28, offset: 3022},
						alternatives: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 135, col: 28, offset: 3022},
								name: "Decimal",
							},
							&ruleRefExpr{
								pos:  position{line: 135, col: 38, offset: 3032},
								name: "Integer",
							},
						},
					},
				},
			},
		},
		{
			name: "EmptyCheck",
			pos:  position{line: 140, col: 2, offset: 3098},
			expr: &choiceExpr{
				pos: position{line: 140, col: 16, offset: 3112},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 140, col: 16, offset: 3112},
						run: (*parser).callonEmptyCheck2,
						expr: &litMatcher{
							pos:        position{line: 140, col: 16, offset: 3112},
							val:        "is empty",
							ignoreCase: false,
							want:       "\"is empty\"",
						},
					},
					&actionExpr{
						pos: position{line: 142, col: 6, offset: 3146},
						run: (*parser).callonEmptyCheck4,
						expr: &litMatcher{
							pos:        position{line: 142, col: 6, offset: 3146},
							val:        "is not empty",
							ignoreCase: false,
							want:       "\"is not empty\"",
						},
					},
				},
			},
		},
		{
			name: "StatementBlock",
			pos:  position{line: 150, col: 2, offset: 3310},
			expr: &actionExpr{
				pos: position{line: 150, col: 20, offset: 3328},
				run: (*parser).callonStatementBlock1,
				expr: &seqExpr{
					pos: position{line: 150, col: 20, offset: 3328},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 150, col: 20, offset: 3328},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 150, col: 22, offset: 3330},
							val:        "{",
							ignoreCase: false,
							want:       "\"{\"",
						},
						&ruleRefExpr{
							pos:  position{line: 150, col: 25, offset: 3333},
							name: "_",
						},
						&zeroOrMoreExpr{
							pos: position{line: 150, col: 27, offset: 3335},
							expr: &seqExpr{
								pos: position{line: 150, col: 28, offset: 3336},
								exprs: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 150, col: 28, offset: 3336},
										name: "Comment",
									},
									&ruleRefExpr{
										pos:  position{line: 150, col: 36, offset: 3344},
										name: "_",
									},
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 150, col: 40, offset: 3348},
							label: "stmt",
							expr: &zeroOrMoreExpr{
								pos: position{line: 150, col: 45, offset: 3353},
								expr: &ruleRefExpr{
									pos:  position{line: 150, col: 46, offset: 3354},
									name: "Statement",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 150, col: 58, offset: 3366},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 150, col: 60, offset: 3368},
							val:        "}",
							ignoreCase: false,
							want:       "\"}\"",
						},
						&ruleRefExpr{
							pos:  position{line: 150, col: 64, offset: 3372},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "Statement",
			pos:  position{line: 160, col: 2, offset: 3555},
			expr: &choiceExpr{
				pos: position{line: 160, col: 15, offset: 3568},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 160, col: 15, offset: 3568},
						run: (*parser).callonStatement2,
						expr: &seqExpr{
							pos: position{line: 160, col: 15, offset: 3568},
							exprs: []interface{}{
								&zeroOrMoreExpr{
									pos: position{line: 160, col: 15, offset: 3568},
									expr: &seqExpr{
										pos: position{line: 160, col: 16, offset: 3569},
										exprs: []interface{}{
											&ruleRefExpr{
												pos:  position{line: 160, col: 16, offset: 3569},
												name: "Comment",
											},
											&ruleRefExpr{
												pos:  position{line: 160, col: 24, offset: 3577},
												name: "_",
											},
										},
									},
								},
								&labeledExpr{
									pos:   position{line: 160, col: 28, offset: 3581},
									label: "stmt",
									expr: &ruleRefExpr{
										pos:  position{line: 160, col: 33, offset: 3586},
										name: "Assignment",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 160, col: 44, offset: 3597},
									name: "_",
								},
								&zeroOrMoreExpr{
									pos: position{line: 160, col: 47, offset: 3600},
									expr: &seqExpr{
										pos: position{line: 160, col: 48, offset: 3601},
										exprs: []interface{}{
											&ruleRefExpr{
												pos:  position{line: 160, col: 48, offset: 3601},
												name: "Comment",
											},
											&ruleRefExpr{
												pos:  position{line: 160, col: 56, offset: 3609},
												name: "_",
											},
										},
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 162, col: 6, offset: 3654},
						run: (*parser).callonStatement15,
						expr: &seqExpr{
							pos: position{line: 162, col: 6, offset: 3654},
							exprs: []interface{}{
								&zeroOrMoreExpr{
									pos: position{line: 162, col: 6, offset: 3654},
									expr: &seqExpr{
										pos: position{line: 162, col: 7, offset: 3655},
										exprs: []interface{}{
											&ruleRefExpr{
												pos:  position{line: 162, col: 7, offset: 3655},
												name: "Comment",
											},
											&ruleRefExpr{
												pos:  position{line: 162, col: 15, offset: 3663},
												name: "_",
											},
										},
									},
								},
								&labeledExpr{
									pos:   position{line: 162, col: 19, offset: 3667},
									label: "stmt",
									expr: &ruleRefExpr{
										pos:  position{line: 162, col: 24, offset: 3672},
										name: "RaiseEvent",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 162, col: 35, offset: 3683},
									name: "_",
								},
								&zeroOrMoreExpr{
									pos: position{line: 162, col: 37, offset: 3685},
									expr: &seqExpr{
										pos: position{line: 162, col: 38, offset: 3686},
										exprs: []interface{}{
											&ruleRefExpr{
												pos:  position{line: 162, col: 38, offset: 3686},
												name: "Comment",
											},
											&ruleRefExpr{
												pos:  position{line: 162, col: 46, offset: 3694},
												name: "_",
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Assignment",
			pos:  position{line: 167, col: 2, offset: 3792},
			expr: &choiceExpr{
				pos: position{line: 167, col: 16, offset: 3806},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 167, col: 16, offset: 3806},
						run: (*parser).callonAssignment2,
						expr: &seqExpr{
							pos: position{line: 167, col: 16, offset: 3806},
							exprs: []interface{}{
								&ruleRefExpr{
									pos:  position{line: 167, col: 16, offset: 3806},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 167, col: 18, offset: 3808},
									label: "lhs",
									expr: &ruleRefExpr{
										pos:  position{line: 167, col: 22, offset: 3812},
										name: "VariableName",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 167, col: 35, offset: 3825},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 167, col: 37, offset: 3827},
									val:        "=",
									ignoreCase: false,
									want:       "\"=\"",
								},
								&ruleRefExpr{
									pos:  position{line: 167, col: 41, offset: 3831},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 167, col: 44, offset: 3834},
									label: "val",
									expr: &ruleRefExpr{
										pos:  position{line: 167, col: 48, offset: 3838},
										name: "ConstString",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 167, col: 60, offset: 3850},
									name: "_",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 173, col: 6, offset: 4055},
						run: (*parser).callonAssignment13,
						expr: &seqExpr{
							pos: position{line: 173, col: 6, offset: 4055},
							exprs: []interface{}{
								&ruleRefExpr{
									pos:  position{line: 173, col: 6, offset: 4055},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 173, col: 8, offset: 4057},
									label: "lhs",
									expr: &ruleRefExpr{
										pos:  position{line: 173, col: 12, offset: 4061},
										name: "VariableName",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 173, col: 25, offset: 4074},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 173, col: 27, offset: 4076},
									val:        "=",
									ignoreCase: false,
									want:       "\"=\"",
								},
								&ruleRefExpr{
									pos:  position{line: 173, col: 31, offset: 4080},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 173, col: 33, offset: 4082},
									label: "val",
									expr: &ruleRefExpr{
										pos:  position{line: 173, col: 37, offset: 4086},
										name: "Expr",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 173, col: 42, offset: 4091},
									name: "_",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 178, col: 6, offset: 4264},
						run: (*parser).callonAssignment24,
						expr: &seqExpr{
							pos: position{line: 178, col: 6, offset: 4264},
							exprs: []interface{}{
								&ruleRefExpr{
									pos:  position{line: 178, col: 6, offset: 4264},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 178, col: 8, offset: 4266},
									label: "lhs",
									expr: &ruleRefExpr{
										pos:  position{line: 178, col: 12, offset: 4270},
										name: "VariableName",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 178, col: 25, offset: 4283},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 178, col: 27, offset: 4285},
									val:        "=",
									ignoreCase: false,
									want:       "\"=\"",
								},
								&ruleRefExpr{
									pos:  position{line: 178, col: 31, offset: 4289},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 178, col: 33, offset: 4291},
									label: "restCommand",
									expr: &ruleRefExpr{
										pos:  position{line: 178, col: 45, offset: 4303},
										name: "RestGet",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 178, col: 53, offset: 4311},
									name: "_",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "RestGet",
			pos:  position{line: 189, col: 2, offset: 4619},
			expr: &actionExpr{
				pos: position{line: 189, col: 13, offset: 4630},
				run: (*parser).callonRestGet1,
				expr: &seqExpr{
					pos: position{line: 189, col: 13, offset: 4630},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 189, col: 13, offset: 4630},
							val:        "GET",
							ignoreCase: false,
							want:       "\"GET\"",
						},
						&ruleRefExpr{
							pos:  position{line: 189, col: 19, offset: 4636},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 189, col: 21, offset: 4638},
							label: "url",
							expr: &ruleRefExpr{
								pos:  position{line: 189, col: 25, offset: 4642},
								name: "ConstString",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 189, col: 37, offset: 4654},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "RaiseEvent",
			pos:  position{line: 198, col: 2, offset: 4810},
			expr: &actionExpr{
				pos: position{line: 198, col: 16, offset: 4824},
				run: (*parser).callonRaiseEvent1,
				expr: &seqExpr{
					pos: position{line: 198, col: 16, offset: 4824},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 198, col: 16, offset: 4824},
							val:        "RAISE EVENT",
							ignoreCase: false,
							want:       "\"RAISE EVENT\"",
						},
						&ruleRefExpr{
							pos:  position{line: 198, col: 30, offset: 4838},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 198, col: 32, offset: 4840},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 198, col: 37, offset: 4845},
								name: "TriggerName",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 198, col: 49, offset: 4857},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 198, col: 51, offset: 4859},
							label: "eventBody",
							expr: &ruleRefExpr{
								pos:  position{line: 198, col: 61, offset: 4869},
								name: "JsonObject",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 198, col: 72, offset: 4880},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "JsonObject",
			pos:  position{line: 203, col: 2, offset: 5003},
			expr: &actionExpr{
				pos: position{line: 203, col: 16, offset: 5017},
				run: (*parser).callonJsonObject1,
				expr: &seqExpr{
					pos: position{line: 203, col: 16, offset: 5017},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 203, col: 16, offset: 5017},
							val:        "{",
							ignoreCase: false,
							want:       "\"{\"",
						},
						&ruleRefExpr{
							pos:  position{line: 203, col: 20, offset: 5021},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 203, col: 22, offset: 5023},
							label: "vals",
							expr: &zeroOrOneExpr{
								pos: position{line: 203, col: 27, offset: 5028},
								expr: &seqExpr{
									pos: position{line: 203, col: 28, offset: 5029},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 203, col: 28, offset: 5029},
											name: "ConstString",
										},
										&ruleRefExpr{
											pos:  position{line: 203, col: 40, offset: 5041},
											name: "_",
										},
										&litMatcher{
											pos:        position{line: 203, col: 42, offset: 5043},
											val:        ":",
											ignoreCase: false,
											want:       "\":\"",
										},
										&ruleRefExpr{
											pos:  position{line: 203, col: 46, offset: 5047},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 203, col: 48, offset: 5049},
											name: "JsonValue",
										},
										&zeroOrMoreExpr{
											pos: position{line: 203, col: 58, offset: 5059},
											expr: &seqExpr{
												pos: position{line: 203, col: 59, offset: 5060},
												exprs: []interface{}{
													&litMatcher{
														pos:        position{line: 203, col: 59, offset: 5060},
														val:        ",",
														ignoreCase: false,
														want:       "\",\"",
													},
													&ruleRefExpr{
														pos:  position{line: 203, col: 63, offset: 5064},
														name: "_",
													},
													&ruleRefExpr{
														pos:  position{line: 203, col: 65, offset: 5066},
														name: "ConstString",
													},
													&ruleRefExpr{
														pos:  position{line: 203, col: 77, offset: 5078},
														name: "_",
													},
													&litMatcher{
														pos:        position{line: 203, col: 79, offset: 5080},
														val:        ":",
														ignoreCase: false,
														want:       "\":\"",
													},
													&ruleRefExpr{
														pos:  position{line: 203, col: 83, offset: 5084},
														name: "_",
													},
													&ruleRefExpr{
														pos:  position{line: 203, col: 85, offset: 5086},
														name: "JsonValue",
													},
												},
											},
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 203, col: 101, offset: 5102},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 203, col: 103, offset: 5104},
							val:        "}",
							ignoreCase: false,
							want:       "\"}\"",
						},
						&ruleRefExpr{
							pos:  position{line: 203, col: 107, offset: 5108},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "JsonValue",
			pos:  position{line: 220, col: 2, offset: 5440},
			expr: &actionExpr{
				pos: position{line: 220, col: 15, offset: 5453},
				run: (*parser).callonJsonValue1,
				expr: &labeledExpr{
					pos:   position{line: 220, col: 15, offset: 5453},
					label: "val",
					expr: &choiceExpr{
						pos: position{line: 220, col: 20, offset: 5458},
						alternatives: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 220, col: 20, offset: 5458},
								name: "JsonObject",
							},
							&ruleRefExpr{
								pos:  position{line: 220, col: 33, offset: 5471},
								name: "ConstString",
							},
							&ruleRefExpr{
								pos:  position{line: 220, col: 47, offset: 5485},
								name: "Decimal",
							},
							&ruleRefExpr{
								pos:  position{line: 220, col: 57, offset: 5495},
								name: "Integer",
							},
							&ruleRefExpr{
								pos:  position{line: 220, col: 67, offset: 5505},
								name: "Bool",
							},
						},
					},
				},
			},
		},
		{
			name:        "NOP",
			displayName: "\"Null OP\"",
			pos:         position{line: 241, col: 2, offset: 5888},
			expr: &seqExpr{
				pos: position{line: 241, col: 19, offset: 5905},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 241, col: 19, offset: 5905},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 241, col: 21, offset: 5907},
						val:        "nop",
						ignoreCase: false,
						want:       "\"nop\"",
					},
					&ruleRefExpr{
						pos:  position{line: 241, col: 27, offset: 5913},
						name: "_",
					},
				},
			},
		},
		{
			name: "Expr",
			pos:  position{line: 247, col: 2, offset: 6044},
			expr: &actionExpr{
				pos: position{line: 247, col: 10, offset: 6052},
				run: (*parser).callonExpr1,
				expr: &seqExpr{
					pos: position{line: 247, col: 10, offset: 6052},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 247, col: 10, offset: 6052},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 247, col: 12, offset: 6054},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 247, col: 18, offset: 6060},
								name: "Term",
							},
						},
						&labeledExpr{
							pos:   position{line: 247, col: 23, offset: 6065},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 247, col: 28, offset: 6070},
								expr: &seqExpr{
									pos: position{line: 247, col: 30, offset: 6072},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 247, col: 30, offset: 6072},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 247, col: 32, offset: 6074},
											name: "AddOp",
										},
										&ruleRefExpr{
											pos:  position{line: 247, col: 38, offset: 6080},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 247, col: 40, offset: 6082},
											name: "Term",
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 247, col: 48, offset: 6090},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "Term",
			pos:  position{line: 267, col: 2, offset: 6418},
			expr: &actionExpr{
				pos: position{line: 267, col: 10, offset: 6426},
				run: (*parser).callonTerm1,
				expr: &seqExpr{
					pos: position{line: 267, col: 10, offset: 6426},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 267, col: 10, offset: 6426},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 267, col: 16, offset: 6432},
								name: "Factor",
							},
						},
						&labeledExpr{
							pos:   position{line: 267, col: 23, offset: 6439},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 267, col: 28, offset: 6444},
								expr: &seqExpr{
									pos: position{line: 267, col: 30, offset: 6446},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 267, col: 30, offset: 6446},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 267, col: 32, offset: 6448},
											name: "MulOp",
										},
										&ruleRefExpr{
											pos:  position{line: 267, col: 38, offset: 6454},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 267, col: 40, offset: 6456},
											name: "Factor",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Factor",
			pos:  position{line: 287, col: 2, offset: 6795},
			expr: &choiceExpr{
				pos: position{line: 287, col: 12, offset: 6805},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 287, col: 12, offset: 6805},
						run: (*parser).callonFactor2,
						expr: &seqExpr{
							pos: position{line: 287, col: 12, offset: 6805},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 287, col: 12, offset: 6805},
									val:        "(",
									ignoreCase: false,
									want:       "\"(\"",
								},
								&labeledExpr{
									pos:   position{line: 287, col: 16, offset: 6809},
									label: "expr",
									expr: &ruleRefExpr{
										pos:  position{line: 287, col: 21, offset: 6814},
										name: "Expr",
									},
								},
								&litMatcher{
									pos:        position{line: 287, col: 26, offset: 6819},
									val:        ")",
									ignoreCase: false,
									want:       "\")\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 289, col: 6, offset: 6849},
						run: (*parser).callonFactor8,
						expr: &labeledExpr{
							pos:   position{line: 289, col: 6, offset: 6849},
							label: "integer",
							expr: &ruleRefExpr{
								pos:  position{line: 289, col: 14, offset: 6857},
								name: "Integer",
							},
						},
					},
				},
			},
		},
		{
			name: "AddOp",
			pos:  position{line: 294, col: 2, offset: 6947},
			expr: &actionExpr{
				pos: position{line: 294, col: 11, offset: 6956},
				run: (*parser).callonAddOp1,
				expr: &choiceExpr{
					pos: position{line: 294, col: 13, offset: 6958},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 294, col: 13, offset: 6958},
							val:        "+",
							ignoreCase: false,
							want:       "\"+\"",
						},
						&litMatcher{
							pos:        position{line: 294, col: 19, offset: 6964},
							val:        "-",
							ignoreCase: false,
							want:       "\"-\"",
						},
					},
				},
			},
		},
		{
			name: "MulOp",
			pos:  position{line: 298, col: 2, offset: 7008},
			expr: &actionExpr{
				pos: position{line: 298, col: 11, offset: 7017},
				run: (*parser).callonMulOp1,
				expr: &choiceExpr{
					pos: position{line: 298, col: 13, offset: 7019},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 298, col: 13, offset: 7019},
							val:        "*",
							ignoreCase: false,
							want:       "\"*\"",
						},
						&litMatcher{
							pos:        position{line: 298, col: 19, offset: 7025},
							val:        "/",
							ignoreCase: false,
							want:       "\"/\"",
						},
					},
				},
			},
		},
		{
			name: "ComparisonOperator",
			pos:  position{line: 302, col: 2, offset: 7068},
			expr: &actionExpr{
				pos: position{line: 302, col: 24, offset: 7090},
				run: (*parser).callonComparisonOperator1,
				expr: &choiceExpr{
					pos: position{line: 302, col: 25, offset: 7091},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 302, col: 25, offset: 7091},
							val:        "==",
							ignoreCase: false,
							want:       "\"==\"",
						},
						&litMatcher{
							pos:        position{line: 302, col: 32, offset: 7098},
							val:        "<=",
							ignoreCase: false,
							want:       "\"<=\"",
						},
						&litMatcher{
							pos:        position{line: 302, col: 39, offset: 7105},
							val:        ">=",
							ignoreCase: false,
							want:       "\">=\"",
						},
						&litMatcher{
							pos:        position{line: 302, col: 46, offset: 7112},
							val:        "!=",
							ignoreCase: false,
							want:       "\"!=\"",
						},
						&litMatcher{
							pos:        position{line: 302, col: 53, offset: 7119},
							val:        "<",
							ignoreCase: false,
							want:       "\"<\"",
						},
						&litMatcher{
							pos:        position{line: 302, col: 59, offset: 7125},
							val:        ">",
							ignoreCase: false,
							want:       "\">\"",
						},
					},
				},
			},
		},
		{
			name: "VariableName",
			pos:  position{line: 310, col: 2, offset: 7295},
			expr: &actionExpr{
				pos: position{line: 310, col: 18, offset: 7311},
				run: (*parser).callonVariableName1,
				expr: &oneOrMoreExpr{
					pos: position{line: 310, col: 18, offset: 7311},
					expr: &ruleRefExpr{
						pos:  position{line: 310, col: 18, offset: 7311},
						name: "FieldChars",
					},
				},
			},
		},
		{
			name: "FieldChars",
			pos:  position{line: 314, col: 2, offset: 7359},
			expr: &actionExpr{
				pos: position{line: 314, col: 16, offset: 7373},
				run: (*parser).callonFieldChars1,
				expr: &charClassMatcher{
					pos:        position{line: 314, col: 16, offset: 7373},
					val:        "[a-zA-Z0-9_\\\\.]",
					chars:      []rune{'_', '\\', '.'},
					ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name: "ConstString",
			pos:  position{line: 318, col: 2, offset: 7424},
			expr: &actionExpr{
				pos: position{line: 318, col: 17, offset: 7439},
				run: (*parser).callonConstString1,
				expr: &seqExpr{
					pos: position{line: 318, col: 17, offset: 7439},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 318, col: 17, offset: 7439},
							val:        "\"",
							ignoreCase: false,
							want:       "\"\\\"\"",
						},
						&zeroOrMoreExpr{
							pos: position{line: 318, col: 21, offset: 7443},
							expr: &choiceExpr{
								pos: position{line: 318, col: 23, offset: 7445},
								alternatives: []interface{}{
									&seqExpr{
										pos: position{line: 318, col: 23, offset: 7445},
										exprs: []interface{}{
											&notExpr{
												pos: position{line: 318, col: 23, offset: 7445},
												expr: &ruleRefExpr{
													pos:  position{line: 318, col: 24, offset: 7446},
													name: "EscapedChar",
												},
											},
											&anyMatcher{
												line: 318, col: 36, offset: 7458,
											},
										},
									},
									&seqExpr{
										pos: position{line: 318, col: 40, offset: 7462},
										exprs: []interface{}{
											&litMatcher{
												pos:        position{line: 318, col: 40, offset: 7462},
												val:        "\\",
												ignoreCase: false,
												want:       "\"\\\\\"",
											},
											&ruleRefExpr{
												pos:  position{line: 318, col: 45, offset: 7467},
												name: "EscapeSequence",
											},
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 318, col: 63, offset: 7485},
							val:        "\"",
							ignoreCase: false,
							want:       "\"\\\"\"",
						},
					},
				},
			},
		},
		{
			name: "EscapedChar",
			pos:  position{line: 323, col: 2, offset: 7601},
			expr: &charClassMatcher{
				pos:        position{line: 323, col: 17, offset: 7616},
				val:        "[\\x00-\\x1f\"\\\\]",
				chars:      []rune{'"', '\\'},
				ranges:     []rune{'\x00', '\x1f'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "EscapeSequence",
			pos:  position{line: 325, col: 2, offset: 7633},
			expr: &choiceExpr{
				pos: position{line: 325, col: 20, offset: 7651},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 325, col: 20, offset: 7651},
						name: "SingleCharEscape",
					},
					&ruleRefExpr{
						pos:  position{line: 325, col: 39, offset: 7670},
						name: "UnicodeEscape",
					},
				},
			},
		},
		{
			name: "SingleCharEscape",
			pos:  position{line: 327, col: 2, offset: 7686},
			expr: &charClassMatcher{
				pos:        position{line: 327, col: 22, offset: 7706},
				val:        "[\"\\\\/bfnrt]",
				chars:      []rune{'"', '\\', '/', 'b', 'f', 'n', 'r', 't'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "UnicodeEscape",
			pos:  position{line: 329, col: 2, offset: 7720},
			expr: &seqExpr{
				pos: position{line: 329, col: 19, offset: 7737},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 329, col: 19, offset: 7737},
						val:        "u",
						ignoreCase: false,
						want:       "\"u\"",
					},
					&ruleRefExpr{
						pos:  position{line: 329, col: 23, offset: 7741},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 329, col: 32, offset: 7750},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 329, col: 41, offset: 7759},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 329, col: 50, offset: 7768},
						name: "HexDigit",
					},
				},
			},
		},
		{
			name: "HexDigit",
			pos:  position{line: 331, col: 2, offset: 7779},
			expr: &charClassMatcher{
				pos:        position{line: 331, col: 14, offset: 7791},
				val:        "[0-9a-f]i",
				ranges:     []rune{'0', '9', 'a', 'f'},
				ignoreCase: true,
				inverted:   false,
			},
		},
		{
			name: "Decimal",
			pos:  position{line: 333, col: 2, offset: 7803},
			expr: &actionExpr{
				pos: position{line: 333, col: 13, offset: 7814},
				run: (*parser).callonDecimal1,
				expr: &seqExpr{
					pos: position{line: 333, col: 13, offset: 7814},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 333, col: 13, offset: 7814},
							expr: &litMatcher{
								pos:        position{line: 333, col: 13, offset: 7814},
								val:        "-",
								ignoreCase: false,
								want:       "\"-\"",
							},
						},
						&oneOrMoreExpr{
							pos: position{line: 333, col: 18, offset: 7819},
							expr: &charClassMatcher{
								pos:        position{line: 333, col: 18, offset: 7819},
								val:        "[0-9]",
								ranges:     []rune{'0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
						&anyMatcher{
							line: 333, col: 24, offset: 7825,
						},
						&oneOrMoreExpr{
							pos: position{line: 333, col: 25, offset: 7826},
							expr: &charClassMatcher{
								pos:        position{line: 333, col: 25, offset: 7826},
								val:        "[0-9]",
								ranges:     []rune{'0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "Integer",
			pos:  position{line: 341, col: 2, offset: 7961},
			expr: &actionExpr{
				pos: position{line: 341, col: 13, offset: 7972},
				run: (*parser).callonInteger1,
				expr: &seqExpr{
					pos: position{line: 341, col: 13, offset: 7972},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 341, col: 13, offset: 7972},
							expr: &litMatcher{
								pos:        position{line: 341, col: 13, offset: 7972},
								val:        "-",
								ignoreCase: false,
								want:       "\"-\"",
							},
						},
						&oneOrMoreExpr{
							pos: position{line: 341, col: 18, offset: 7977},
							expr: &charClassMatcher{
								pos:        position{line: 341, col: 18, offset: 7977},
								val:        "[0-9]",
								ranges:     []rune{'0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "Bool",
			pos:  position{line: 345, col: 2, offset: 8029},
			expr: &choiceExpr{
				pos: position{line: 345, col: 10, offset: 8037},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 345, col: 10, offset: 8037},
						run: (*parser).callonBool2,
						expr: &litMatcher{
							pos:        position{line: 345, col: 10, offset: 8037},
							val:        "true",
							ignoreCase: false,
							want:       "\"true\"",
						},
					},
					&actionExpr{
						pos: position{line: 345, col: 40, offset: 8067},
						run: (*parser).callonBool4,
						expr: &litMatcher{
							pos:        position{line: 345, col: 40, offset: 8067},
							val:        "false",
							ignoreCase: false,
							want:       "\"false\"",
						},
					},
				},
			},
		},
		{
			name: "Comment",
			pos:  position{line: 347, col: 2, offset: 8099},
			expr: &seqExpr{
				pos: position{line: 347, col: 13, offset: 8110},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 347, col: 13, offset: 8110},
						val:        "//",
						ignoreCase: false,
						want:       "\"//\"",
					},
					&zeroOrMoreExpr{
						pos: position{line: 347, col: 18, offset: 8115},
						expr: &charClassMatcher{
							pos:        position{line: 347, col: 18, offset: 8115},
							val:        "[^\\r\\n]",
							chars:      []rune{'\r', '\n'},
							ignoreCase: false,
							inverted:   true,
						},
					},
				},
			},
		},
		{
			name:        "_",
			displayName: "\"whitespace\"",
			pos:         position{line: 349, col: 2, offset: 8126},
			expr: &zeroOrMoreExpr{
				pos: position{line: 349, col: 20, offset: 8144},
				expr: &charClassMatcher{
					pos:        position{line: 349, col: 20, offset: 8144},
					val:        "[ \\n\\t\\r]",
					chars:      []rune{' ', '\n', '\t', '\r'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 351, col: 2, offset: 8157},
			expr: &notExpr{
				pos: position{line: 351, col: 9, offset: 8164},
				expr: &anyMatcher{
					line: 351, col: 10, offset: 8165,
				},
			},
		},
	},
}

func (c *current) onInput1(root, condition, conditions interface{}) (interface{}, error) {
	container := &ast.RuleContainer{}
	container.Trigger = root.(ast.IAstNode)

	choiceBlock := &ast.ChoiceNode{}
	choiceBlock.AddChoice(condition.(ast.IAstNode))

	for _, otherRules := range splitComponents(conditions) {
		altRule := splitComponents(otherRules)
		decodedRule := altRule[2].(ast.IAstNode)
		choiceBlock.AddChoice(decodedRule)
	}

	container.Plan = choiceBlock

	return container, nil

}

func (p *parser) callonInput1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInput1(stack["root"], stack["condition"], stack["conditions"])
}

func (c *current) onTrigger1(eventName interface{}) (interface{}, error) {
	triggerNode := &ast.TriggerNode{EventName: eventName.(string)}
	return ast.IAstNode(triggerNode), nil

}

func (p *parser) callonTrigger1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTrigger1(stack["eventName"])
}

func (c *current) onTriggerName1() (interface{}, error) {
	return string(c.text), nil

}

func (p *parser) callonTriggerName1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTriggerName1()
}

func (c *current) onCondition1(ruleField, block interface{}) (interface{}, error) {

	astBlock := &ast.ConditionBlock{}

	if astBlock == nil {
		panic("Cant create AST")
	}

	for _, ruleElements := range splitComponents(ruleField) {
		rule := splitComponents(ruleElements)

		if node, isAstNode := rule[0].(ast.IAstNode); isAstNode {
			currentRule := node
			astBlock.AddCondition(currentRule)
		}
	}
	astBlock.Action = block.(ast.IAstNode)

	return ast.IAstNode(astBlock), nil

}

func (p *parser) callonCondition1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCondition1(stack["ruleField"], stack["block"])
}

func (c *current) onRuleField1(first, alt interface{}) (interface{}, error) {
	firstRule := first.(ast.IAstNode)

	otherRules := splitComponents(alt)

	if otherRules != nil {
		altRule := otherRules[2].(ast.IAstNode)

		altNode := &ast.AltClauseNode{
			Lhs: firstRule,
			Rhs: altRule,
			Op:  "OR",
		}
		return altNode, nil
	}

	return firstRule, nil

}

func (p *parser) callonRuleField1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRuleField1(stack["first"], stack["alt"])
}

func (c *current) onRuleClause2(field, null interface{}) (interface{}, error) {
	ruleField := field.(string)

	lhs := &ast.VariableNode{}
	lhs.Name = ruleField

	rhs := &ast.VariableNode{}
	rhs.Name = "empty"

	astCondition := &ast.ConditionNode{}

	if null == 1 {
		astCondition.Op = "=="
	} else {
		astCondition.Op = "!="
	}

	astCondition.Lhs = lhs
	astCondition.Rhs = rhs

	return astCondition, nil

}

func (p *parser) callonRuleClause2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRuleClause2(stack["field"], stack["null"])
}

func (c *current) onRuleClause10(field, op, rhs interface{}) (interface{}, error) {
	ruleField := field.(string)

	lhs := &ast.VariableNode{}
	lhs.Name = ruleField

	decodedVal := rhs.(ast.IAstNode)

	astCondition := &ast.ConditionNode{lhs, decodedVal, op.(string)}

	return astCondition, nil

}

func (p *parser) callonRuleClause10() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRuleClause10(stack["field"], stack["op"], stack["rhs"])
}

func (c *current) onConditionValue1(rhsVal interface{}) (interface{}, error) {
	val := &ast.ValueNode{rhsVal}
	return val, nil

}

func (p *parser) callonConditionValue1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onConditionValue1(stack["rhsVal"])
}

func (c *current) onEmptyCheck2() (interface{}, error) {
	return 1, nil

}

func (p *parser) callonEmptyCheck2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEmptyCheck2()
}

func (c *current) onEmptyCheck4() (interface{}, error) {
	return 0, nil

}

func (p *parser) callonEmptyCheck4() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEmptyCheck4()
}

func (c *current) onStatementBlock1(stmt interface{}) (interface{}, error) {
	block := &ast.BlockNode{}

	for _, curStatement := range splitComponents(stmt) {
		block.AddStatement(curStatement.(ast.IAstNode))

	}
	return ast.IAstNode(block), nil

}

func (p *parser) callonStatementBlock1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStatementBlock1(stack["stmt"])
}

func (c *current) onStatement2(stmt interface{}) (interface{}, error) {
	return stmt.(ast.IAstNode), nil

}

func (p *parser) callonStatement2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStatement2(stack["stmt"])
}

func (c *current) onStatement15(stmt interface{}) (interface{}, error) {
	return stmt.(ast.IAstNode), nil

}

func (p *parser) callonStatement15() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStatement15(stack["stmt"])
}

func (c *current) onAssignment2(lhs, val interface{}) (interface{}, error) {
	assignmentName := lhs.(string)
	assignmentRhs := &ast.ValueNode{val.(string)}

	assignmentNode := &ast.AssignmentNode{assignmentName, assignmentRhs}
	return ast.IAstNode(assignmentNode), nil

}

func (p *parser) callonAssignment2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAssignment2(stack["lhs"], stack["val"])
}

func (c *current) onAssignment13(lhs, val interface{}) (interface{}, error) {
	assignmentNode := &ast.AssignmentNode{}
	assignmentNode.Name = lhs.(string)
	assignmentNode.Rhs = val.(ast.IAstNode)
	return ast.IAstNode(assignmentNode), nil

}

func (p *parser) callonAssignment13() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAssignment13(stack["lhs"], stack["val"])
}

func (c *current) onAssignment24(lhs, restCommand interface{}) (interface{}, error) {
	assignmentNode := &ast.AssignmentNode{}
	assignmentNode.Name = lhs.(string)
	assignmentNode.Rhs = restCommand.(ast.IAstNode)
	return ast.IAstNode(assignmentNode), nil

}

func (p *parser) callonAssignment24() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAssignment24(stack["lhs"], stack["restCommand"])
}

func (c *current) onRestGet1(url interface{}) (interface{}, error) {
	addressParam := &ast.ValueNode{url.(string)}

	node := &ast.CommandNode{Command: "GET"}
	node.AddParameter(addressParam)

	return node, nil

}

func (p *parser) callonRestGet1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRestGet1(stack["url"])
}

func (c *current) onRaiseEvent1(name, eventBody interface{}) (interface{}, error) {
	node := &ast.RaiseEventNode{EventName: name.(string), MessageBody: eventBody.(ast.IAstNode)}
	return node, nil

}

func (p *parser) callonRaiseEvent1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRaiseEvent1(stack["name"], stack["eventBody"])
}

func (c *current) onJsonObject1(vals interface{}) (interface{}, error) {
	node := ast.CreateJsonBodyNode()

	entries := splitComponents(vals)

	node.Entries[entries[0].(string)] = entries[4]

	moreEntries := splitComponents(entries[5])

	for _, e := range moreEntries {
		nextVal := splitComponents(e)
		node.Entries[nextVal[2].(string)] = nextVal[6]
	}

	return ast.IAstNode(node), nil

}

func (p *parser) callonJsonObject1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onJsonObject1(stack["vals"])
}

func (c *current) onJsonValue1(val interface{}) (interface{}, error) {
	var retVal ast.IAstNode

	switch val.(type) {
	case ast.IAstNode:
		retVal = val.(ast.IAstNode)
	case int:
		retVal = &ast.ValueNode{val}
	case string:
		retVal = &ast.ValueNode{val}
	case float32:
		retVal = &ast.ValueNode{val}
	case float64:
		retVal = &ast.ValueNode{val}
	case bool:
		retVal = &ast.ValueNode{val}
	}
	return retVal, nil

}

func (p *parser) callonJsonValue1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onJsonValue1(stack["val"])
}

func (c *current) onExpr1(first, rest interface{}) (interface{}, error) {
	lhs := first.(ast.IAstNode)

	rawRhs := splitComponents(rest)

	for _, v := range rawRhs {
		restExpr := splitComponents(v)

		op := restExpr[1].(string)

		rhs := restExpr[3].(ast.IAstNode)

		exprNode := &ast.ExpressionNode{lhs, rhs, op}

		lhs = ast.IAstNode(exprNode)
	}

	return ast.IAstNode(lhs), nil

}

func (p *parser) callonExpr1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExpr1(stack["first"], stack["rest"])
}

func (c *current) onTerm1(first, rest interface{}) (interface{}, error) {
	lhs := first.(ast.IAstNode)

	rawRhs := splitComponents(rest)

	for _, v := range rawRhs {
		restExpr := splitComponents(v)

		op := restExpr[1].(string)

		rhs := restExpr[3].(ast.IAstNode)

		exprNode := &ast.ExpressionNode{lhs, rhs, op}

		lhs = ast.IAstNode(exprNode)
	}

	return ast.IAstNode(lhs), nil

}

func (p *parser) callonTerm1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTerm1(stack["first"], stack["rest"])
}

func (c *current) onFactor2(expr interface{}) (interface{}, error) {
	return expr, nil

}

func (p *parser) callonFactor2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFactor2(stack["expr"])
}

func (c *current) onFactor8(integer interface{}) (interface{}, error) {
	intNode := &ast.ValueNode{integer}
	return ast.IAstNode(intNode), nil

}

func (p *parser) callonFactor8() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFactor8(stack["integer"])
}

func (c *current) onAddOp1() (interface{}, error) {
	return string(c.text), nil

}

func (p *parser) callonAddOp1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAddOp1()
}

func (c *current) onMulOp1() (interface{}, error) {
	return string(c.text), nil

}

func (p *parser) callonMulOp1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMulOp1()
}

func (c *current) onComparisonOperator1() (interface{}, error) {
	return string(c.text), nil

}

func (p *parser) callonComparisonOperator1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onComparisonOperator1()
}

func (c *current) onVariableName1() (interface{}, error) {
	return string(c.text), nil

}

func (p *parser) callonVariableName1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onVariableName1()
}

func (c *current) onFieldChars1() (interface{}, error) {
	return string(c.text), nil

}

func (p *parser) callonFieldChars1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFieldChars1()
}

func (c *current) onConstString1() (interface{}, error) {
	c.text = bytes.Replace(c.text, []byte(`\/`), []byte(`/`), -1)
	return strconv.Unquote(string(c.text))

}

func (p *parser) callonConstString1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onConstString1()
}

func (c *current) onDecimal1() (interface{}, error) {
	if val, err := strconv.ParseFloat(string(c.text), 32); err == nil {
		return float32(val), err
	}

	return 0.0, nil

}

func (p *parser) callonDecimal1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDecimal1()
}

func (c *current) onInteger1() (interface{}, error) {
	return strconv.Atoi(string(c.text))

}

func (p *parser) callonInteger1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInteger1()
}

func (c *current) onBool2() (interface{}, error) {
	return true, nil
}

func (p *parser) callonBool2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBool2()
}

func (c *current) onBool4() (interface{}, error) {
	return false, nil
}

func (p *parser) callonBool4() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBool4()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//     input := "input"
//     stats := Stats{}
//     _, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//     if err != nil {
//         log.Panicln(err)
//     }
//     b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//     if err != nil {
//         log.Panicln(err)
//     }
//     fmt.Println(string(b))
//
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i interface{}, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (interface{}, error) {
	b, err := ioutil.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (interface{}, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]interface{}

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        interface{}
}

type choiceExpr struct {
	pos          position
	alternatives []interface{}
}

type actionExpr struct {
	pos  position
	expr interface{}
	run  func(*parser) (interface{}, error)
}

type recoveryExpr struct {
	pos          position
	expr         interface{}
	recoverExpr  interface{}
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []interface{}
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  interface{}
}

type expr struct {
	pos  position
	expr interface{}
}

type andExpr expr
type notExpr expr
type zeroOrOneExpr expr
type zeroOrMoreExpr expr
type oneOrMoreExpr expr

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   interface{}
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[interface{}]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]interface{}
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]interface{}
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]interface{})
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr interface{}) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]interface{}, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) in(s string) string {
	p.depth++
	return p.print(strings.Repeat(" ", p.depth)+">", s)
}

func (p *parser) out(s string) string {
	p.depth--
	return p.print(strings.Repeat(" ", p.depth)+"<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() interface{}
}

var statePool = &sync.Pool{
	New: func() interface{} { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node interface{}) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node interface{}, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[interface{}]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[interface{}]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val interface{}, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRule(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRule(rule *rule) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}

	if p.memoize {
		res, ok := p.getMemoized(rule)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
	}

	start := p.pt
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExpr(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}

	if p.memoize {
		p.setMemoized(start, rule, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr interface{}) (interface{}, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val interface{}
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExpr(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExpr(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExpr(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExpr(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExpr(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExpr(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRule(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]interface{}, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExpr(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExpr(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExpr(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
